### ISSUE TITLE
[BUG/ISSUE] Appears Not to Work with Forge 47.1.0

### ISSUE THREAD

**Issue by DumbXBoxAcct** [CERBON-MODS/Just-Enough-Beacons#1]
## Before submitting the issue

- [Yes] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [Yes - v. 1.19+-1.0.0 for Forge] **I have checked that I am running the latest version of Just Enough Beacons**
- [Yes] **I have read the [contributing guidelines](https://github.com/CerbonXD/BetterTotemOfUndying/blob/master/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/CerbonXD/BetterTotemOfUndying/blob/master/CODE_OF_CONDUCT.md)**

## Minecraft Version
Minecraft 1.20.1, Forge v. 47.1.0

## Describe the bug
No tabs for Beacon Base Blocks, Beacon Payments or Conduit Frame Blocks when a beacon is clicked in JEI's menu of items. 

## To Reproduce
1. Load Forge 47.1.0, JEI 15.2.027 for Forge & Just Enough Beacons Reforged 1.19+-1.0.0
2. Search JEI for "beacon"
3. Click the beacon item in the resulting panel
4. A single tab for Crafting appears, but none of the three Just Enough Beacons tabs appear

## Expected behavior
When clicking the beacon item in JEI, a panel with a Crafting tab, plus the the three expected tabs added by Just Enough Beacons Reforged should appear.

## Screenshots
![Splash Screen Showing Version](https://github.com/CERBON-MODS/Just-Enough-Beacons/assets/115334190/f4c532f0-981a-4b36-8be5-a4af70484d7b)
![JEI Screen 1](https://github.com/CERBON-MODS/Just-Enough-Beacons/assets/115334190/49c96aa0-35e9-4ad4-acc5-1c4ab55b207e)
![JEI Screen 2](https://github.com/CERBON-MODS/Just-Enough-Beacons/assets/115334190/ee0116ae-227c-414f-b6fc-e64dfc3276e4)

## Latest Log
[latest.log](https://github.com/CERBON-MODS/Just-Enough-Beacons/files/12602483/latest.log)
[debug.log](https://github.com/CERBON-MODS/Just-Enough-Beacons/files/12602484/debug.log)

</details>

**Comment by CerbonXD** [comment]
Just to be sure, have you tried right clicking it?

**Comment by DumbXBoxAcct** [comment]
That worked, thank you, Felipe!Was needing to right-click it somewhere on the Curseforge page and I just missed it?  I don’t recall seeing it.  If not, it probably would be helpful to put it in the mod description there so that you avoid a bunch of people bothering you for a nonexistent issue!Thanks for your speedy response, I really appreciate it.- GordonOn Sep 13, 2023, at 8:54 PM, Felipe Cerboncini ***@***.***> wrote:﻿
Just to be sure, have you tried right clicking it?

**Comment by CerbonXD** [comment]
No problem. 

No, this is not an information at the description. I think I'm gonna add it to make things clearer. Thank you.
